
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action SeznamMP3Action;
	
	private global::Gtk.Action Action;
	
	private global::Gtk.Action editAction;
	
	private global::Gtk.Action closeAction;
	
	private global::Gtk.RadioAction selectMultipleAction;
	
	private global::Gtk.RadioAction selectSingleAction;
	
	private global::Gtk.Action goForwardAction;
	
	private global::Gtk.Action goBackAction;
	
	private global::Gtk.ToggleAction editingModeAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action addAction;
	
	private global::Gtk.Action removeAction;
	
	private global::Gtk.Action changeLanguageAction;
	
	private global::Gtk.Action selectAction;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.Fixed @fixed;
	
	private global::Gtk.Notebook notebook;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView tree;
	
	private global::Gtk.Label labelID3v1Tree;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView tree2;
	
	private global::Gtk.Label labelID3v2Tree;
	
	private global::Gtk.Toolbar mainToolbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.SeznamMP3Action = new global::Gtk.Action ("SeznamMP3Action", global::Mono.Unix.Catalog.GetString ("Seznam MP3"), null, null);
		this.SeznamMP3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Seznam MP3");
		w1.Add (this.SeznamMP3Action, null);
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		w1.Add (this.Action, null);
		this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Edit"), global::Mono.Unix.Catalog.GetString ("Edit"), "gtk-edit");
		this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.editAction, null);
		this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Close "), global::Mono.Unix.Catalog.GetString ("Close"), "gtk-close");
		this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.closeAction, null);
		this.selectMultipleAction = new global::Gtk.RadioAction ("selectMultipleAction", global::Mono.Unix.Catalog.GetString ("Edit multi"), global::Mono.Unix.Catalog.GetString ("Edit multi"), "gtk-dnd-multiple", 0);
		this.selectMultipleAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.selectMultipleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit multi");
		w1.Add (this.selectMultipleAction, null);
		this.selectSingleAction = new global::Gtk.RadioAction ("selectSingleAction", global::Mono.Unix.Catalog.GetString ("Edit single"), global::Mono.Unix.Catalog.GetString ("Edit single"), "gtk-dnd", 0);
		this.selectSingleAction.Group = this.selectMultipleAction.Group;
		this.selectSingleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit single");
		w1.Add (this.selectSingleAction, null);
		this.goForwardAction = new global::Gtk.Action ("goForwardAction", global::Mono.Unix.Catalog.GetString ("Next"), global::Mono.Unix.Catalog.GetString ("Next"), "gtk-go-forward");
		this.goForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next");
		w1.Add (this.goForwardAction, null);
		this.goBackAction = new global::Gtk.Action ("goBackAction", global::Mono.Unix.Catalog.GetString ("Previous"), global::Mono.Unix.Catalog.GetString ("Previous"), "gtk-go-back");
		this.goBackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous");
		w1.Add (this.goBackAction, null);
		this.editingModeAction = new global::Gtk.ToggleAction ("editingModeAction", global::Mono.Unix.Catalog.GetString ("Edit cells"), global::Mono.Unix.Catalog.GetString ("Edit cells"), "gtk-index");
		this.editingModeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit Cells");
		w1.Add (this.editingModeAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), global::Mono.Unix.Catalog.GetString ("Save"), "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction, null);
		this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("Add"), global::Mono.Unix.Catalog.GetString ("Add"), "gtk-add");
		this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add");
		w1.Add (this.addAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", global::Mono.Unix.Catalog.GetString ("Remove"), global::Mono.Unix.Catalog.GetString ("Remove"), "gtk-remove");
		this.removeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove");
		w1.Add (this.removeAction, null);
		this.changeLanguageAction = new global::Gtk.Action ("changeLanguageAction", global::Mono.Unix.Catalog.GetString ("Language"), global::Mono.Unix.Catalog.GetString ("Language"), "gtk-select-font");
		this.changeLanguageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Language");
		w1.Add (this.changeLanguageAction, null);
		this.selectAction = new global::Gtk.Action ("selectAction", global::Mono.Unix.Catalog.GetString ("Select"), global::Mono.Unix.Catalog.GetString ("Select"), "gtk-select-all");
		this.selectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select");
		w1.Add (this.selectAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("Info"), global::Mono.Unix.Catalog.GetString ("Info"), "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Info");
		w1.Add (this.dialogInfoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MP3 Tagger");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.@fixed = new global::Gtk.Fixed ();
		this.@fixed.Name = "fixed";
		this.@fixed.HasWindow = false;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.notebook = new global::Gtk.Notebook ();
		this.notebook.WidthRequest = 800;
		this.notebook.HeightRequest = 600;
		this.notebook.CanFocus = true;
		this.notebook.Name = "notebook";
		this.notebook.CurrentPage = 0;
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tree = new global::Gtk.TreeView ();
		this.tree.CanFocus = true;
		this.tree.Name = "tree";
		this.GtkScrolledWindow.Add (this.tree);
		this.notebook.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.labelID3v1Tree = new global::Gtk.Label ();
		this.labelID3v1Tree.Name = "labelID3v1Tree";
		this.labelID3v1Tree.LabelProp = global::Mono.Unix.Catalog.GetString ("TAG 1");
		this.notebook.SetTabLabel (this.GtkScrolledWindow, this.labelID3v1Tree);
		this.labelID3v1Tree.ShowAll ();
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tree2 = new global::Gtk.TreeView ();
		this.tree2.CanFocus = true;
		this.tree2.Name = "tree2";
		this.GtkScrolledWindow1.Add (this.tree2);
		this.notebook.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.GtkScrolledWindow1]));
		w5.Position = 1;
		// Notebook tab
		this.labelID3v2Tree = new global::Gtk.Label ();
		this.labelID3v2Tree.Name = "labelID3v2Tree";
		this.labelID3v2Tree.LabelProp = global::Mono.Unix.Catalog.GetString ("TAG 2");
		this.notebook.SetTabLabel (this.GtkScrolledWindow1, this.labelID3v2Tree);
		this.labelID3v2Tree.ShowAll ();
		this.@fixed.Add (this.notebook);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.notebook]));
		w6.X = 4;
		w6.Y = 54;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='mainToolbar'><toolitem name='addAction' action='addAction'/><toolitem name='removeAction' action='removeAction'/><separator/><toolitem name='editAction' action='editAction'/><separator/><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><separator/><toolitem name='selectSingleAction' action='selectSingleAction'/><toolitem name='selectMultipleAction' action='selectMultipleAction'/><toolitem name='editingModeAction' action='editingModeAction'/><separator/><toolitem name='selectAction' action='selectAction'/><separator/><toolitem name='changeLanguageAction' action='changeLanguageAction'/><toolitem name='dialogInfoAction' action='dialogInfoAction'/><separator/><toolitem name='saveAction' action='saveAction'/><separator/><toolitem name='closeAction' action='closeAction'/></toolbar></ui>");
		this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/mainToolbar")));
		this.mainToolbar.Name = "mainToolbar";
		this.mainToolbar.ShowArrow = false;
		this.mainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(3));
		this.mainToolbar.IconSize = ((global::Gtk.IconSize)(3));
		this.@fixed.Add (this.mainToolbar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.mainToolbar]));
		w7.X = 5;
		this.Add (this.@fixed);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 836;
		this.DefaultHeight = 706;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
		this.editAction.Activated += new global::System.EventHandler (this.OnEditActionActivated);
		this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.selectMultipleAction.Activated += new global::System.EventHandler (this.OnDndMultipleActionActivated);
		this.selectSingleAction.Activated += new global::System.EventHandler (this.OnSelectSingleActionActivated);
		this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
		this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
		this.editingModeAction.Activated += new global::System.EventHandler (this.OnEditingModeActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.addAction.Activated += new global::System.EventHandler (this.OnAddActionActivated);
		this.removeAction.Activated += new global::System.EventHandler (this.OnRemoveActionActivated);
		this.changeLanguageAction.Activated += new global::System.EventHandler (this.OnChangeLanguageActionActivated);
		this.selectAction.Activated += new global::System.EventHandler (this.OnSelectActionActivated);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.OnDialogInfoActionActivated);
	}
}
