
// This file has been generated by the GUI designer. Do not modify.
namespace MP3Tagger
{
	public partial class TagWidget
	{
		private global::Gtk.Fixed @fixed;
		private global::Gtk.Entry entryTitle;
		private global::Gtk.Label labelTitle;
		private global::Gtk.Label labelArtist;
		private global::Gtk.Entry entryArtist;
		private global::Gtk.Entry entryAlbum;
		private global::Gtk.Entry entryYear;
		private global::Gtk.Label labelAlbum;
		private global::Gtk.Label labelYear;
		private global::Gtk.Label labelGenre;
		private global::Gtk.Label labelComment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textViewComment;
		private global::Gtk.ComboBox comboBoxGenre;
		private global::Gtk.Label labelTrackNumber;
		private global::Gtk.Entry entryTrackNumber;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MP3Tagger.TagWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MP3Tagger.TagWidget";
			// Container child MP3Tagger.TagWidget.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryTitle = new global::Gtk.Entry ();
			this.entryTitle.WidthRequest = 250;
			this.entryTitle.CanFocus = true;
			this.entryTitle.Name = "entryTitle";
			this.entryTitle.IsEditable = true;
			this.entryTitle.InvisibleChar = '●';
			this.@fixed.Add (this.entryTitle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryTitle]));
			w1.X = 75;
			w1.Y = 22;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.@fixed.Add (this.labelTitle);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTitle]));
			w2.X = 5;
			w2.Y = 26;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelArtist = new global::Gtk.Label ();
			this.labelArtist.Name = "labelArtist";
			this.labelArtist.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist");
			this.@fixed.Add (this.labelArtist);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelArtist]));
			w3.X = 5;
			w3.Y = 55;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryArtist = new global::Gtk.Entry ();
			this.entryArtist.WidthRequest = 250;
			this.entryArtist.CanFocus = true;
			this.entryArtist.Name = "entryArtist";
			this.entryArtist.IsEditable = true;
			this.entryArtist.InvisibleChar = '●';
			this.@fixed.Add (this.entryArtist);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryArtist]));
			w4.X = 75;
			w4.Y = 52;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryAlbum = new global::Gtk.Entry ();
			this.entryAlbum.WidthRequest = 250;
			this.entryAlbum.CanFocus = true;
			this.entryAlbum.Name = "entryAlbum";
			this.entryAlbum.IsEditable = true;
			this.entryAlbum.InvisibleChar = '●';
			this.@fixed.Add (this.entryAlbum);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryAlbum]));
			w5.X = 75;
			w5.Y = 80;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryYear = new global::Gtk.Entry ();
			this.entryYear.WidthRequest = 50;
			this.entryYear.CanFocus = true;
			this.entryYear.Name = "entryYear";
			this.entryYear.IsEditable = true;
			this.entryYear.InvisibleChar = '●';
			this.@fixed.Add (this.entryYear);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryYear]));
			w6.X = 75;
			w6.Y = 108;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelAlbum = new global::Gtk.Label ();
			this.labelAlbum.Name = "labelAlbum";
			this.labelAlbum.LabelProp = global::Mono.Unix.Catalog.GetString ("Album");
			this.@fixed.Add (this.labelAlbum);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelAlbum]));
			w7.X = 5;
			w7.Y = 85;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelYear = new global::Gtk.Label ();
			this.labelYear.Name = "labelYear";
			this.labelYear.LabelProp = global::Mono.Unix.Catalog.GetString ("Year");
			this.@fixed.Add (this.labelYear);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelYear]));
			w8.X = 5;
			w8.Y = 114;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelGenre = new global::Gtk.Label ();
			this.labelGenre.Name = "labelGenre";
			this.labelGenre.LabelProp = global::Mono.Unix.Catalog.GetString ("Genre");
			this.@fixed.Add (this.labelGenre);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelGenre]));
			w9.X = 5;
			w9.Y = 144;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelComment = new global::Gtk.Label ();
			this.labelComment.Name = "labelComment";
			this.labelComment.LabelProp = global::Mono.Unix.Catalog.GetString ("Comment");
			this.@fixed.Add (this.labelComment);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelComment]));
			w10.X = 5;
			w10.Y = 175;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textViewComment = new global::Gtk.TextView ();
			this.textViewComment.WidthRequest = 250;
			this.textViewComment.CanFocus = true;
			this.textViewComment.Name = "textViewComment";
			this.GtkScrolledWindow.Add (this.textViewComment);
			this.@fixed.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.GtkScrolledWindow]));
			w12.X = 75;
			w12.Y = 175;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.comboBoxGenre = global::Gtk.ComboBox.NewText ();
			this.comboBoxGenre.WidthRequest = 250;
			this.comboBoxGenre.Name = "comboBoxGenre";
			this.@fixed.Add (this.comboBoxGenre);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.comboBoxGenre]));
			w13.X = 75;
			w13.Y = 139;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelTrackNumber = new global::Gtk.Label ();
			this.labelTrackNumber.Name = "labelTrackNumber";
			this.labelTrackNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Track Number");
			this.@fixed.Add (this.labelTrackNumber);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelTrackNumber]));
			w14.X = 180;
			w14.Y = 114;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryTrackNumber = new global::Gtk.Entry ();
			this.entryTrackNumber.WidthRequest = 50;
			this.entryTrackNumber.CanFocus = true;
			this.entryTrackNumber.Name = "entryTrackNumber";
			this.entryTrackNumber.IsEditable = true;
			this.entryTrackNumber.InvisibleChar = '●';
			this.@fixed.Add (this.entryTrackNumber);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryTrackNumber]));
			w15.X = 276;
			w15.Y = 108;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
