
// This file has been generated by the GUI designer. Do not modify.
namespace MP3Tagger
{
	public partial class InfoWin
	{
		private global::Gtk.Fixed @fixed;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Button buttonOK;
		private global::Gtk.Label labelVer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MP3Tagger.InfoWin
			this.Name = "MP3Tagger.InfoWin";
			this.Title = global::Mono.Unix.Catalog.GetString ("InfoWin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MP3Tagger.InfoWin.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("MP3Tagger 4 (beta)");
			this.@fixed.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.label2]));
			w1.X = 16;
			w1.Y = 16;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("http://github.com/petrj/MP3Tagger");
			this.@fixed.Add (this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.label3]));
			w2.X = 16;
			w2.Y = 55;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			// Container child buttonOK.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("OK");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.buttonOK.Add (w3);
			this.@fixed.Add (this.buttonOK);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonOK]));
			w11.X = 331;
			w11.Y = 137;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelVer = new global::Gtk.Label ();
			this.labelVer.Name = "labelVer";
			this.labelVer.LabelProp = global::Mono.Unix.Catalog.GetString ("nightbuild (2015.01.23)");
			this.@fixed.Add (this.labelVer);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelVer]));
			w12.X = 16;
			w12.Y = 92;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 193;
			this.Show ();
			this.buttonOK.Clicked += new global::System.EventHandler (this.OnButtonOKClicked);
		}
	}
}
