
// This file has been generated by the GUI designer. Do not modify.
namespace MP3Tagger
{
	public partial class SongDetail
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action goForwardAction;
		private global::Gtk.Action goBackAction;
		private global::Gtk.Action editAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action applyAction;
		private global::Gtk.Action undoAction;
		private global::Gtk.Action closeAction1;
		private global::Gtk.Fixed @fixed;
		private global::Gtk.Toolbar toolbar;
		private global::Gtk.Entry entryFileName;
		private global::Gtk.Label labelFName;
		private global::Gtk.CheckButton checkButtonID31Active;
		private global::Gtk.CheckButton checkButtonID32Active;
		private global::Gtk.Notebook notebook;
		private global::Gtk.Fixed fixedTAG1;
		private global::MP3Tagger.TagWidget tagWidget1;
		private global::Gtk.Label labelTAG1;
		private global::Gtk.Fixed fixedTAG2;
		private global::MP3Tagger.TagWidget tagWidget2;
		private global::Gtk.Label labelTAG2;
		private global::Gtk.Fixed fixedTAG2Frames;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeViewFrames;
		private global::Gtk.Label labelTAG2Frames;
		private global::Gtk.Fixed fixedImages;
		private global::Gtk.Label labelCoverFront;
		private global::Gtk.Image imageCoverFront;
		private global::Gtk.Button buttonSetFrontCoverImage;
		private global::Gtk.Label labelTAG2Image;
		private global::Gtk.Button buttonMaskHelp;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MP3Tagger.SongDetail
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", global::Mono.Unix.Catalog.GetString ("Next"), null, "gtk-go-forward");
			this.goForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next");
			w1.Add (this.goForwardAction, null);
			this.goBackAction = new global::Gtk.Action ("goBackAction", global::Mono.Unix.Catalog.GetString ("Previous"), null, "gtk-go-back");
			this.goBackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous");
			w1.Add (this.goBackAction, null);
			this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, "gtk-edit");
			this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.editAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
			w1.Add (this.closeAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
			w1.Add (this.saveAction, null);
			this.applyAction = new global::Gtk.Action ("applyAction", global::Mono.Unix.Catalog.GetString ("klk"), null, "gtk-apply");
			this.applyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("OK");
			w1.Add (this.applyAction, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("Undo"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
			w1.Add (this.undoAction, null);
			this.closeAction1 = new global::Gtk.Action ("closeAction1", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
			this.closeAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
			w1.Add (this.closeAction1, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MP3Tagger.SongDetail";
			this.Title = global::Mono.Unix.Catalog.GetString ("SongDetail");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MP3Tagger.SongDetail.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar'><toolitem name='applyAction' action='applyAction'/><separator/><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><separator/><toolitem name='undoAction' action='undoAction'/><separator/><toolitem name='closeAction1' action='closeAction1'/></toolbar></ui>");
			this.toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar")));
			this.toolbar.Name = "toolbar";
			this.toolbar.ShowArrow = false;
			this.@fixed.Add (this.toolbar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.toolbar]));
			w2.X = 3;
			w2.Y = 6;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.entryFileName = new global::Gtk.Entry ();
			this.entryFileName.WidthRequest = 265;
			this.entryFileName.CanFocus = true;
			this.entryFileName.Name = "entryFileName";
			this.entryFileName.IsEditable = true;
			this.entryFileName.InvisibleChar = '●';
			this.@fixed.Add (this.entryFileName);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.entryFileName]));
			w3.X = 85;
			w3.Y = 73;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelFName = new global::Gtk.Label ();
			this.labelFName.Name = "labelFName";
			this.labelFName.LabelProp = global::Mono.Unix.Catalog.GetString ("Filename");
			this.@fixed.Add (this.labelFName);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelFName]));
			w4.X = 15;
			w4.Y = 77;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.checkButtonID31Active = new global::Gtk.CheckButton ();
			this.checkButtonID31Active.CanFocus = true;
			this.checkButtonID31Active.Name = "checkButtonID31Active";
			this.checkButtonID31Active.Label = global::Mono.Unix.Catalog.GetString ("TAG 1");
			this.checkButtonID31Active.Active = true;
			this.checkButtonID31Active.DrawIndicator = true;
			this.checkButtonID31Active.UseUnderline = true;
			this.@fixed.Add (this.checkButtonID31Active);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.checkButtonID31Active]));
			w5.X = 11;
			w5.Y = 112;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.checkButtonID32Active = new global::Gtk.CheckButton ();
			this.checkButtonID32Active.CanFocus = true;
			this.checkButtonID32Active.Name = "checkButtonID32Active";
			this.checkButtonID32Active.Label = global::Mono.Unix.Catalog.GetString ("TAG 2");
			this.checkButtonID32Active.DrawIndicator = true;
			this.checkButtonID32Active.UseUnderline = true;
			this.@fixed.Add (this.checkButtonID32Active);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.checkButtonID32Active]));
			w6.X = 85;
			w6.Y = 112;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.HeightRequest = 300;
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 0;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.fixedTAG1 = new global::Gtk.Fixed ();
			this.fixedTAG1.Name = "fixedTAG1";
			this.fixedTAG1.HasWindow = false;
			// Container child fixedTAG1.Gtk.Fixed+FixedChild
			this.tagWidget1 = new global::MP3Tagger.TagWidget ();
			this.tagWidget1.Events = ((global::Gdk.EventMask)(256));
			this.tagWidget1.Name = "tagWidget1";
			this.fixedTAG1.Add (this.tagWidget1);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixedTAG1 [this.tagWidget1]));
			w7.X = 5;
			w7.Y = 5;
			this.notebook.Add (this.fixedTAG1);
			// Notebook tab
			this.labelTAG1 = new global::Gtk.Label ();
			this.labelTAG1.Name = "labelTAG1";
			this.labelTAG1.Xpad = 8;
			this.labelTAG1.LabelProp = global::Mono.Unix.Catalog.GetString ("TAG1");
			this.notebook.SetTabLabel (this.fixedTAG1, this.labelTAG1);
			this.labelTAG1.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.fixedTAG2 = new global::Gtk.Fixed ();
			this.fixedTAG2.Name = "fixedTAG2";
			this.fixedTAG2.HasWindow = false;
			// Container child fixedTAG2.Gtk.Fixed+FixedChild
			this.tagWidget2 = new global::MP3Tagger.TagWidget ();
			this.tagWidget2.Events = ((global::Gdk.EventMask)(256));
			this.tagWidget2.Name = "tagWidget2";
			this.fixedTAG2.Add (this.tagWidget2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixedTAG2 [this.tagWidget2]));
			w9.X = 5;
			w9.Y = 5;
			this.notebook.Add (this.fixedTAG2);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.fixedTAG2]));
			w10.Position = 1;
			// Notebook tab
			this.labelTAG2 = new global::Gtk.Label ();
			this.labelTAG2.Name = "labelTAG2";
			this.labelTAG2.Xpad = 8;
			this.labelTAG2.LabelProp = global::Mono.Unix.Catalog.GetString ("TAG2");
			this.notebook.SetTabLabel (this.fixedTAG2, this.labelTAG2);
			this.labelTAG2.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.fixedTAG2Frames = new global::Gtk.Fixed ();
			this.fixedTAG2Frames.Name = "fixedTAG2Frames";
			this.fixedTAG2Frames.HasWindow = false;
			// Container child fixedTAG2Frames.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeViewFrames = new global::Gtk.TreeView ();
			this.treeViewFrames.WidthRequest = 350;
			this.treeViewFrames.HeightRequest = 230;
			this.treeViewFrames.CanFocus = true;
			this.treeViewFrames.Name = "treeViewFrames";
			this.GtkScrolledWindow2.Add (this.treeViewFrames);
			this.fixedTAG2Frames.Add (this.GtkScrolledWindow2);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixedTAG2Frames [this.GtkScrolledWindow2]));
			w12.X = 5;
			w12.Y = 5;
			this.notebook.Add (this.fixedTAG2Frames);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.fixedTAG2Frames]));
			w13.Position = 2;
			// Notebook tab
			this.labelTAG2Frames = new global::Gtk.Label ();
			this.labelTAG2Frames.Name = "labelTAG2Frames";
			this.labelTAG2Frames.Xpad = 8;
			this.labelTAG2Frames.LabelProp = global::Mono.Unix.Catalog.GetString ("TAG2 - frames");
			this.notebook.SetTabLabel (this.fixedTAG2Frames, this.labelTAG2Frames);
			this.labelTAG2Frames.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.fixedImages = new global::Gtk.Fixed ();
			this.fixedImages.Name = "fixedImages";
			this.fixedImages.HasWindow = false;
			// Container child fixedImages.Gtk.Fixed+FixedChild
			this.labelCoverFront = new global::Gtk.Label ();
			this.labelCoverFront.Name = "labelCoverFront";
			this.labelCoverFront.LabelProp = global::Mono.Unix.Catalog.GetString ("Front Cover");
			this.fixedImages.Add (this.labelCoverFront);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixedImages [this.labelCoverFront]));
			w14.X = 11;
			w14.Y = 16;
			// Container child fixedImages.Gtk.Fixed+FixedChild
			this.imageCoverFront = new global::Gtk.Image ();
			this.imageCoverFront.Name = "imageCoverFront";
			this.fixedImages.Add (this.imageCoverFront);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixedImages [this.imageCoverFront]));
			w15.X = 18;
			w15.Y = 45;
			// Container child fixedImages.Gtk.Fixed+FixedChild
			this.buttonSetFrontCoverImage = new global::Gtk.Button ();
			this.buttonSetFrontCoverImage.CanFocus = true;
			this.buttonSetFrontCoverImage.Name = "buttonSetFrontCoverImage";
			this.buttonSetFrontCoverImage.UseUnderline = true;
			this.buttonSetFrontCoverImage.Label = global::Mono.Unix.Catalog.GetString ("Browse ...");
			this.fixedImages.Add (this.buttonSetFrontCoverImage);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixedImages [this.buttonSetFrontCoverImage]));
			w16.X = 97;
			w16.Y = 10;
			this.notebook.Add (this.fixedImages);
			global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.fixedImages]));
			w17.Position = 3;
			w17.TabExpand = true;
			// Notebook tab
			this.labelTAG2Image = new global::Gtk.Label ();
			this.labelTAG2Image.Name = "labelTAG2Image";
			this.labelTAG2Image.LabelProp = global::Mono.Unix.Catalog.GetString ("Images");
			this.notebook.SetTabLabel (this.fixedImages, this.labelTAG2Image);
			this.labelTAG2Image.ShowAll ();
			this.@fixed.Add (this.notebook);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.notebook]));
			w18.X = 3;
			w18.Y = 140;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.buttonMaskHelp = new global::Gtk.Button ();
			this.buttonMaskHelp.CanFocus = true;
			this.buttonMaskHelp.Name = "buttonMaskHelp";
			this.buttonMaskHelp.UseUnderline = true;
			// Container child buttonMaskHelp.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w20.Add (w23);
			w19.Add (w20);
			this.buttonMaskHelp.Add (w19);
			this.@fixed.Add (this.buttonMaskHelp);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonMaskHelp]));
			w27.X = 355;
			w27.Y = 72;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 396;
			this.DefaultHeight = 470;
			this.Show ();
			this.Shown += new global::System.EventHandler (this.OnShown);
			this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
			this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
			this.applyAction.Activated += new global::System.EventHandler (this.OnApplyActionActivated);
			this.undoAction.Activated += new global::System.EventHandler (this.OnCancelActionActivated);
			this.closeAction1.Activated += new global::System.EventHandler (this.OnCloseAction1Activated);
			this.checkButtonID32Active.Clicked += new global::System.EventHandler (this.OnCheckButtonID32ActiveClicked);
			this.buttonSetFrontCoverImage.Clicked += new global::System.EventHandler (this.OnButtonSetFrontCoverImageClicked);
			this.buttonMaskHelp.Activated += new global::System.EventHandler (this.OnButtonMaskHelpActivated);
			this.buttonMaskHelp.Clicked += new global::System.EventHandler (this.OnButtonMaskHelpClicked);
		}
	}
}
