
// This file has been generated by the GUI designer. Do not modify.
namespace MP3Tagger
{
	public partial class InfoWin
	{
		private global::Gtk.Fixed @fixed;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Button buttonOK;
		
		private global::Gtk.Label labelVer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MP3Tagger.InfoWin
			this.Name = "MP3Tagger.InfoWin";
			this.Title = global::Mono.Unix.Catalog.GetString ("InfoWin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			// Container child MP3Tagger.InfoWin.Gtk.Container+ContainerChild
			this.@fixed = new global::Gtk.Fixed ();
			this.@fixed.Name = "fixed";
			this.@fixed.HasWindow = false;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("MP3Tagger 4 (beta)");
			this.@fixed.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.label2]));
			w1.X = 16;
			w1.Y = 16;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("http://github.com/petrj/MP3Tagger");
			this.@fixed.Add (this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.label3]));
			w2.X = 16;
			w2.Y = 55;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.buttonOK = new global::Gtk.Button ();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			this.buttonOK.Label = global::Mono.Unix.Catalog.GetString ("OK");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.buttonOK.Image = w3;
			this.@fixed.Add (this.buttonOK);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.buttonOK]));
			w4.X = 331;
			w4.Y = 137;
			// Container child fixed.Gtk.Fixed+FixedChild
			this.labelVer = new global::Gtk.Label ();
			this.labelVer.Name = "labelVer";
			this.labelVer.LabelProp = global::Mono.Unix.Catalog.GetString ("nightbuild (2015.10.22)");
			this.@fixed.Add (this.labelVer);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed [this.labelVer]));
			w5.X = 16;
			w5.Y = 92;
			this.Add (this.@fixed);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 405;
			this.DefaultHeight = 212;
			this.Show ();
			this.buttonOK.Clicked += new global::System.EventHandler (this.OnButtonOKClicked);
		}
	}
}
